name: Submodule
on:
  workflow_dispatch:
jobs:
  submodule:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with: 
          token: ${{ secrets.TOKEN_ACTION }}
          fetch-depth: 0
          submodules: true
      - name: update submodule
        run: |
          git config --global url."https://x-access-token:${{ secrets.TOKEN_ACTION }}@github.com".insteadOf git://github
          git submodule update --init --recursive --remote --merge
      - uses: qoomon/actions--setup-git@v1.1.1
        env:
          token: ${{ secrets.TOKEN_ACTION }}
        with:
          user: bot

      - run: |
          git add .
          git commit -m "chore: update all submodule"
          git push
